.TH "utils::Timer" 3 "Version 1.0" "Cuda Examples" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils::Timer
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <utils\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimer\fP ()"
.br
.ti -1c
.RI "\fB~Timer\fP ()"
.br
.ti -1c
.RI "void \fBon\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBelapsed\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fButils\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "utils::Timer::Timer ()"

.PP
Definition at line \fB8\fP of file \fButils\&.cpp\fP\&.
.SS "utils::Timer::~Timer ()"

.PP
Definition at line \fB10\fP of file \fButils\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void utils::Timer::elapsed ()"

.PP
Definition at line \fB18\fP of file \fButils\&.cpp\fP\&.
.SS "void utils::Timer::on (const std::string & name)"

.PP
Definition at line \fB12\fP of file \fButils\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cuda Examples from the source code\&.
